Adding parameter checking - First step
zhongkaifu/Seq2SeqSharp pull request #79
Opened 2023-11-07 09:41 UTC by zsogitbe

We need to check carefully which values each input parameter may have. We also need to check what are the most optimal values for what application. Etc. 

TODO: check and validate all values. Correct if needed.

2023-11-07 09:46 UTC, zsogitbe commented
This will be more work. This is just the start of it.

2023-11-07 14:48 UTC, zhongkaifu commented
Hi @zsogitbe 
It looks pretty useful to automatically verify if the parameter is valid.
How does it work if the parameter is invalid? When will the .NET runtime check the parameters? (Will the parameter be checked when it's called everytime?) I checked some documents, but they are all bout ASP.NET MVC web application, can this attribute be used for other types of application, such as console, web service ?

2023-11-07 14:59 UTC, zsogitbe commented
Hi Zhongkai,

 

Yes, it is very important because we have a lot of parameters and the quality of the models depend on them!

 

So, what we have started is the first step. We need to make sure that we know and set all ranges and possible values (enums) of all variables. 

 

The second step is the automatic checking of these variables. This can be done, for example, by saving a json schema automatically of the input variables based on the annotations we have introduced. The schema can then be used to check all parameters if they are valid. Or even more interesting, we can also suggest to the user automatically to change some of the variables for obtaining better results… But, the annotations we introduce can probably also be used in another way not using json for checking the parameter values at runtime.

 

Best regards,

Zoli

 

 

From: Zhongkai Fu ***@***.***> 
Sent: Tuesday, 7 November 2023 15:49
To: zhongkaifu/Seq2SeqSharp ***@***.***>
Cc: Zoli Somogyi ***@***.***>; Mention ***@***.***>
Subject: Re: [zhongkaifu/Seq2SeqSharp] Adding parameter checking - First step (PR #79)

 

Hi @zsogitbe <https://github.com/zsogitbe> 
It looks pretty useful to automatically verify if the parameter is valid.
How does it work if the parameter is invalid? When will the .NET runtime check the parameters? (Will the parameter be checked when it's called everytime?) I checked some documents, but they are all bout ASP.NET MVC web application, can this attribute be used for other types of application, such as console, web service ?

—
Reply to this email directly, view it on GitHub <https://github.com/zhongkaifu/Seq2SeqSharp/pull/79#issuecomment-1798728940> , or unsubscribe <https://github.com/notifications/unsubscribe-auth/AGI2BAEIJX5ZNUHY4KLSW5TYDJC5LAVCNFSM6AAAAAA7A34FLCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTOOJYG4ZDQOJUGA> .
You are receiving this because you were mentioned.  <https://github.com/notifications/beacon/AGI2BAH7W3S53ATVYKL4K73YDJC5LA5CNFSM6AAAAAA7A34FLCWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTLGZWOY.gif> Message ID: ***@***.*** ***@***.***> >

2023-11-07 17:45 UTC, zhongkaifu requested changes
Leave some comments about the ranges of some parameters.

2023-11-07 17:45 UTC, zhongkaifu commented on Seq2SeqSharp/Applications/Options.cs
> +        [Range(0.0f, 999.0f)]
Its range is [0.0, 1.0]

2023-11-07 17:45 UTC, zhongkaifu commented on Seq2SeqSharp/Applications/Options.cs
> +        [Range(0.0f, 999.9f)]
Its range is [0.0, 1.0]

2023-11-07 17:45 UTC, zhongkaifu commented on Seq2SeqSharp/Applications/Options.cs
> +        [Range(1, 8192)]
It could be larger than 8192. We could set it to [1, 102400] for now

2023-11-07 17:45 UTC, zhongkaifu commented on Seq2SeqSharp/Applications/Options.cs
> +        [Range(0.000000001f, 1.0f)]
It could be 0 if users want to freeze the layers, so the range should be [0.0, 1.0]

2023-11-07 17:45 UTC, zhongkaifu commented on Seq2SeqSharp/Applications/Options.cs
> +        [Range(1, 8192)]
8192 is too small for LLM. Let's set its range to [0, 102400]

2023-11-07 17:45 UTC, zhongkaifu commented on Seq2SeqSharp/Applications/Options.cs
> +        [Range(1, 8192)]
8192 is too small. Let's set its range to [0, 409600]

2023-11-07 17:45 UTC, zhongkaifu commented on Seq2SeqSharp/Applications/Options.cs
> +        [RegularExpression("None|INT8|INT4")]
It also supports FLOAT16

2023-11-07 17:45 UTC, zhongkaifu commented on Seq2SeqSharp/Applications/Seq2SeqOptions.cs
> +        [Range(0.0f, 100.0f)]
Its range is [0.0, 1.0]

2023-11-07 17:45 UTC, zhongkaifu commented on Seq2SeqSharp/Applications/Seq2SeqOptions.cs
> +        [Range(1, 9999)]
Let's set it to a larger range for longer text. For example: [1, 1280000]

2023-11-07 17:45 UTC, zhongkaifu commented on Seq2SeqSharp/Applications/Seq2SeqOptions.cs
> +        [Range(1, 9999)]
Let's set it to a larger range for longer text. For example: [1, 1280000]

2023-11-07 17:45 UTC, zhongkaifu commented on Seq2SeqSharp/Applications/Seq2SeqOptions.cs
> +        [Range(1, 9999)]
Let's set it to a larger range for longer text. For example: [1, 1280000]

2023-11-07 17:45 UTC, zhongkaifu commented on Seq2SeqSharp/Applications/Seq2SeqOptions.cs
> +        [Range(1, 9999)]
Let's set it to a larger range for longer text. For example: [1, 1280000]

2023-11-07 17:45 UTC, zhongkaifu commented on Seq2SeqSharp/Applications/Seq2SeqOptions.cs
> +        [Range(1, 8192)]
Let's set it to [1, 102400] for larger model.

2023-11-07 17:45 UTC, zhongkaifu commented on Seq2SeqSharp/Applications/SeqClassificationOptions.cs
> +        [Range(1, 99999)]
Let's set it to a larger range for longer text. For example: [1, 1280000]

2023-11-08 17:16 UTC, zhongkaifu approved these changes
Thanks. It looks good to me.

2023-11-08 17:16 UTC, merged